openapi: 3.0.3
info:
  title: Auto Payment API
  description: API for balance replenishment and order payment
  version: 1.0.0
tags:
  - name: Account
    description: Account operations
servers:
  - url: http://yp-pay-app:8081
    description: Dev server
paths:
  /api/accounts/{userId}:
    get:
      summary: Get current balance
      operationId: getBalance
      tags:
        - Account
      parameters:
        - name: userId
          in: path
          description: User id
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          $ref: '#/components/responses/SuccessfulResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
    put:
      summary: Execute operation like deposit or payment
      tags:
        - Account
      operationId: updateBalance
      parameters:
        - name: userId
          in: path
          description: User id
          required: true
          schema:
            type: integer
            example: 1
        - name: operation
          in: query
          description: Operation to be applied over user related account
          required: true
          schema:
            type: string
            enum:
              - deposit
              - payment
            example: deposit
        - name: amount
          in: query
          description: The amount by which the balance will need to be either increased or decreased within the transaction
          required: true
          schema:
            type: number
            format: double
            example: 10000.00
      responses:
        '200':
          $ref: '#/components/responses/SuccessfulResponse'
        '404':
          $ref: '#/components/responses/ErrorResponse'
        '500':
          $ref: '#/components/responses/ErrorResponse'
components:
  responses:
    SuccessfulResponse:
      description: Successful response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BalanceResponse'
    ErrorResponse:
      description: Error response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
  schemas:
    BalanceResponse:
      type: object
      properties:
        balance:
          type: number
          format: double
          example: 10000.00
    ErrorResponse:
      type: object
      properties:
        status:
          type: string
          example: NOT_FOUND
        message:
          type: string
          example: User not found
        timestamp:
          type: string
          format: date-time
          example: 2026-01-01T00:00:00Z